# Generated by Django 5.0.7 on 2024-07-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
