# Generated by Django 5.0.7 on 2024-07-12 13:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('image_1', models.ImageField(default='', null=True, upload_to='images')),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('image_4', models.ImageField(blank=True, default='', null=True, upload_to='images')),
            ],
        ),
    ]
