# Generated by Django 5.0.7 on 2024-07-17 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0003_select_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
