# Generated by Django 5.0.7 on 2024-07-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('order', '0001_initial'),
        ('product', '0003_select_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('sell_price', models.FloatField(default=0)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('stock_status', models.IntegerField(choices=[('1', 'in stock'), ('0', 'out of stock')], default=1)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('product', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('total_amount', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
    ]
