# Generated by Django 5.0.7 on 2024-07-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_detail_ordermaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='sell_price',
        ),
    ]
