# Generated by Django 5.0.7 on 2024-07-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_detail_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='courier_charges',
            field=models.FloatField(default=0),
        ),
    ]
